# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  prepared_statements: false
  host: localhost
  username: zero_db
  password: popcornDB!

development:
  <<: *default
  database: experience_app_dev

test:
  <<: *default
  database: experience_app_test

production:
  <<: *default
  database: experience_app_prod
